### PR TITLE
J2534: use XML file for library info (Linux), refactoring, helper functions

### PR DESCRIPTION
**Pull request by SubaruDieselCrew**
No need to hardcode J2534 Linux library anymore.
Building on Windows not tested!

Still C++98 compliant but please keep thinking about switching to C++11, even util functions would benefit from new style already, I would like to upgrade some code accordingly over time. Btw, building Qt 5.7+ itself will depend on a C++11 compiler.

Added minor UI changes in the meantime, not related to J2534.

### CODE REVIEW

**Comment by Comer352L** [comment]
Looks good. :-)

Btw, a new J2534 version has been released last year. Did you already have a chance to take a look at it ?
I wouldn't be surprised if they had standardized library handling on non-Windows systems in the meantime. OS market changed much during the last 11 years... ;-)
Anyway, I'm fine with the XML-list.

What interface is the library you are using for ?
I wonder if you shouldn't select a more specific name...

Will test the Windows changes tomorrow...

**Comment by SubaruDieselCrew** [comment]
I am not aware of newer J2534 standards. Hardly any interface devices targeted for car owners or small shops like tuners seem to support J2534. Usually both commercial and free software are tied to one or a few specific devices, using proprietary APIs. Actually, during my commercial jobs, I never saw J2534 in use at all.
I wanted to check in a demo/easy-to-edit XML file `definitions/J2534Libs.xml`, and at the same time avoid having to constantly mess with replacing the XML file for testing. That way I can run the app directly from build dir, w/o any code changes or additional build tasks or merging branches back and forth etc.
As for default XML content I deliberately used lib name & path `libj2534.so` to provide rather generic naming. Personally, I use a symbolic link that redirects to my actual lib, outside any FreeSSM folders. The lib itself is my own stuff, connects to virtual simulator I wrote in C# some years ago...

**Comment by Comer352L** [comment]
Am 09.02.2016 um 10:13 schrieb SubaruDieselCrew:
> I am not aware of newer J2534 standards.
http://standards.sae.org/j2534/1_201510/

> Hardly any interface devices targeted for car owners or small shops
> like tuners seem to support J2534. Usually both commercial and free
> software are tied to one or a few specific devices, using proprietary
> APIs.
Not this software ! :-)

> Actually, during my commercial jobs, I never saw J2534 in use at all.
At least not directly.
Some (more or less) professional workshop equipment uses J2534 internally.
Sometimes they just don't register the library properly, sometimes it is
not 100% compliant...

**Comment by L1800Turbo** [comment]
Hi,
as an example I know Bosch. They use such a driver if you want to flash an
ECU with data from an OEM.
For their KTS diagnostic system they call it J2534 driver, of course I
don't know if it works complete by standard.

2016-02-09 19:12 GMT+01:00 Comer352L <notifications@github.com>:

**Comment by Comer352L** [comment]
Patches applied and pushed out.
I also added some minor fixes.
git played some weird games with me during testing... investigating... (bug ?)

Thanks !

**Comment by SubaruDieselCrew** [comment]
Tested, works for me (Linux, J2534lib).
Windows build also running (Qt Creator + MinGW), can't test device communication - no sim setup there yet.

OEM software (dealerships/mechanics) is a different story - expensive tools - not for end-users. Btw, _SSM-III_ even in 2011 still used J2534 v0202 + additional proprietary API under the hood, also supplied a v0404 DLL for possible 3rd party apps. Not sure about latest versions, though.

As for J2534 201510: Preview info (TOC etc.) still only mentions "DLL" several times, therefore I am guessing it's still Windows-only. At least they added chapter: _64-bit vs. 32-bit OS_.

**Pull request closed without merging**
