### PR TITLE
minor bugfix (dlclose); util improvements (StrToHexstr)

### PR DESCRIPTION
**Pull request by SubaruDieselCrew**
* I added `-std=c++14` in order to use C++ 14 language standard - newer features is the main motivation to brush up my C++ skills, also makes code safer and sometimes even faster. Hope that's fine with you guys!
* I can only test the app using my own libJ2534.so which connects to a virtual ECU simulator, working fine. Since I don't have any real hardware, I cannot test other interface related stuff. Trying to be careful with changes, though.

### CODE REVIEW

**Comment by Comer352L** [comment]
Looks good, with one exception:
c++14 is supported by g++ since v4.8, but older versions are still widespread.
So can you please avoid that change ? Should be no problem...

**Comment by SubaruDieselCrew** [comment]
I can easily backport those little changes to c++98. Btw, I am using my Linux distro's normal gcc package, current version 5.3.0, which defaults to gnu++98 if `-std=...` is not provided.

AFAIK big (automotive) embedded production code like ECU firmware often still has to stick to c++98 compilers, there are good reasons for that. But as for a PC application like FreeSSM I don't get it. My motivation to contribute bigger changes using old school C++ is really low. Publishing a fork would confuse users - which version to use - not my intention.

Please consider targeting c++11 at least, now in the year 2016 after all. [C++11](https://en.wikipedia.org/wiki/C%2B%2B11), ISO-approved 2011-August, already features simple constexpr stuff, move constructors, better initializer-lists etc.
Let us know your decision, perhaps also future plans, i.e. upgrading from TinyXML to [TinyXML-2](http://www.grinninglizard.com/tinyxml2/) ?

**Comment by Comer352L** [comment]
I'm not generally against using newer C++ standards. If there are some real benefits for the code - fine.
But this minor change IMHO is not worth breaking backwards compatibility.
For future changes - we will see. :-)
C++14 is pretty new, lets try cope with C++11 first.

**Comment by SubaruDieselCrew** [comment]
Fair enough.
I have been reviewing C++11 changes vs. C++98 and C++03 lately. My decision is to not use anything below C++11 for hobby projects, unless for minor bug fixes etc. I just like the language improvements a lot already. Paid work is a totally different story of course, no problem coding old school Fortran if required...
As for FreeSSM in particular, I might try to add logging into file (.csv) - AFAIK still missing, no guarantees though...

**Comment by SubaruDieselCrew** [comment]
Plz check and merge if you haven't seen the last commit already.

**Comment by Comer352L** [comment]
Excellent, thanks.

**Pull request merged**
