### PR TITLE
refactorings and optimizations, no new features yet

### PR DESCRIPTION
**Pull request by SubaruDieselCrew**
Warning: only SSM2 has been tested (both CAN and K-Line transports, ECU & TCU), cannot test SSM1!

* I did double-check important modified code like bytenr & bitmasks --> flagbytebit().

* Feel free to review and merge if you like. I will probably switch to C++11 soon, use more standard library features etc.

* As for planned feature "log to CSV file", I think dumping raw values of switches (0 or 1) is a reasonable solution. I did the same in my C# logger years ago. ASCII in (big) CSV files is too painful and cannot be plotted/analyzed easily. CSV column header text could describe the meaning of the raw value like "0=Off; 1=On".

### CODE REVIEW

**Comment by johanpza** [comment]
Log to CSV would a killer feature, thanks.

**Comment by Comer352L** [comment]
Thank you Martin.
Didn't have time to look at this stuff yet, but the plan is to review both pull request this weekend.
Thanks for you patience !

**Comment by Comer352L** [comment]
Excellent work.
I will do some tests with SSM1 this week (and fix things if necessary).
Thanks !

**Comment by SubaruDieselCrew** [comment]
Glad you like it.
Please also check out my branch "c++11", try to compile and test at least. I will do further stuff there, already contains some modified GUI.

**Pull request merged**
